edit quick start for UG
AY2223S2-CS2103T-W12-4/tp pull request #67
Opened 2023-03-27 14:43 UTC by runoutofit

2023-03-27 14:53 UTC, redHat-arko requested changes

2023-03-27 14:53 UTC, redHat-arko commented on docs/UserGuide.md
> +##Table of Contents
Change this line

2023-03-28 00:10 UTC, zxisatree approved these changes
LGTM

2023-03-28 03:11 UTC, redHat-arko approved these changes

2023-03-28 04:33 UTC, merged